# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b7d3d5a47cef7e05edfdf9aa1148c05df2a727211167fec4113cafa09d34b1e7eeb8545ab987c6387f6ca0fd4f7a5c0bcfd7b7bee5b2bb1c7ab2b9da1c9235

test:
  secret_key_base: e7542041d461ce375af0b1eaf4c8b3599fb4f3e18f3853c4e5d0ac0105b8ace6ab84f61ce8a45963e81ec09b7f885ee1270002e5b9127a95d41c2b8898ce5d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
